title: "[Idea] "
labels: ["idea"]
body:
  - type: textarea
    id: idea
    attributes:
      label: What's the idea?
      description: A short description of what you'd like to see.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Why does this matter?
      description: What problem does it solve, or what value would it add?
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Additional notes
    validations:
      required: false
